#!/bin/bash

chunkc core::log_file   stdout
chunkc core::plugin_dir $HOME/.config/chunkwm/plugins
chunkc core::hotload    0

# chunkwm-tiling plugin:
chunkc set global_desktop_mode           bsp
chunkc set global_desktop_offset_top     0
chunkc set global_desktop_offset_bottom  0
chunkc set global_desktop_offset_left    0
chunkc set global_desktop_offset_right   0
chunkc set global_desktop_offset_gap     1

chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.42

chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle            monitor

chunkc set mouse_follows_focus           intrinsic
chunkc set window_float_next             0
chunkc set window_region_locked          1

chunkc set preselect_border_color        0xffd75f5f
chunkc set preselect_border_width        8
chunkc set preselect_border_radius       0
chunkc set preselect_border_outline      0


# Plugins:
chunkc core::load tiling.so

# chunkwm-tiling rules:
chunkc tiling::rule --owner \"Finder\" --name Copy --state float &
chunkc tiling::rule --owner \"App Store\" --state float &
chunkc tiling::rule --owner \"Karabiner-Elements\" --state float &
chunkc tiling::rule --owner \"Calculator\" --state float &
# chunkc tiling::rule --owner \"GoLand\" --except \"~/Projects/\" --state float &
